# fly.toml app configuration file generated for scriptius on 2026-04-07T05:37:55+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scriptius'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
